# Generated by Django 5.2.4 on 2026-03-21 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productreview',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
    ]
