# Generated by Django 5.2.4 on 2026-03-21 18:58

import apps.products.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_productreview_is_approved'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productimage',
            name='image_data',
        ),
        migrations.RemoveField(
            model_name='productimage',
            name='thumbnail_data',
        ),
        migrations.AddField(
            model_name='productimage',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=apps.products.models.product_upload_to),
        ),
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=apps.products.models.category_upload_to),
        ),
        migrations.AlterField(
            model_name='manufacturer',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to=apps.products.models.manufacturer_upload_to),
        ),
    ]
