# Generated by Django 5.2.4 on 2026-03-24 11:55

import apps.products.models
import storages.backends.s3
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_alter_category_image_alter_manufacturer_logo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.ImageField(blank=True, null=True, storage=storages.backends.s3.S3Storage(bucket_name='lifeline-media'), upload_to=apps.products.models.category_upload_to),
        ),
        migrations.AlterField(
            model_name='manufacturer',
            name='logo',
            field=models.ImageField(blank=True, null=True, storage=storages.backends.s3.S3Storage(bucket_name='lifeline-media'), upload_to=apps.products.models.manufacturer_upload_to),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='image',
            field=models.ImageField(blank=True, null=True, storage=storages.backends.s3.S3Storage(bucket_name='lifeline-media'), upload_to=apps.products.models.product_upload_to),
        ),
    ]
