# Generated by Django 5.2.4 on 2026-03-21 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='prescription_image',
            field=models.ImageField(blank=True, null=True, upload_to='prescriptions/'),
        ),
    ]
