# Generated by Django 5.2.4 on 2026-03-24 11:55

import storages.backends.s3
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_alter_order_prescription_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='prescription_image',
            field=models.ImageField(blank=True, null=True, storage=storages.backends.s3.S3Storage(bucket_name='lifeline-media'), upload_to='prescriptions/'),
        ),
    ]
