# Generated by Django 5.2.4 on 2026-03-21 18:58

import apps.accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientprofile',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to=apps.accounts.models.patient_profile_upload_to),
        ),
        migrations.AlterField(
            model_name='pharmacyprofile',
            name='gst_certificate',
            field=models.FileField(blank=True, null=True, upload_to=apps.accounts.models.pharmacy_document_upload_to),
        ),
        migrations.AlterField(
            model_name='pharmacyprofile',
            name='license_document',
            field=models.FileField(blank=True, null=True, upload_to=apps.accounts.models.pharmacy_document_upload_to),
        ),
    ]
