# Generated by Django 5.2.4 on 2026-03-24 11:55

import apps.accounts.models
import storages.backends.s3
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_patientprofile_profile_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientprofile',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, storage=storages.backends.s3.S3Storage(bucket_name='lifeline-media'), upload_to=apps.accounts.models.patient_profile_upload_to),
        ),
        migrations.AlterField(
            model_name='pharmacyprofile',
            name='gst_certificate',
            field=models.FileField(blank=True, null=True, storage=storages.backends.s3.S3Storage(bucket_name='lifeline-media'), upload_to=apps.accounts.models.pharmacy_document_upload_to),
        ),
        migrations.AlterField(
            model_name='pharmacyprofile',
            name='license_document',
            field=models.FileField(blank=True, null=True, storage=storages.backends.s3.S3Storage(bucket_name='lifeline-media'), upload_to=apps.accounts.models.pharmacy_document_upload_to),
        ),
    ]
