# Generated by Django 5.2.4 on 2026-03-31 11:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_patientprofile_profile_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patientprofile',
            name='emergency_contact_name',
        ),
        migrations.RemoveField(
            model_name='patientprofile',
            name='emergency_contact_phone',
        ),
    ]
