# Generated by Django 5.2.4 on 2025-08-26 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_carouselimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='carouselimage',
            name='image_upload',
            field=models.ImageField(blank=True, help_text='Upload source image (will be converted to base64)', null=True, upload_to='carousel_uploads/'),
        ),
        migrations.AlterField(
            model_name='carouselimage',
            name='image_data',
            field=models.TextField(blank=True),
        ),
    ]
