# Generated by Django 5.2.4 on 2026-03-21 18:58

import apps.core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_carouselimage_image_upload_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carouselimage',
            name='image_data',
        ),
        migrations.RemoveField(
            model_name='carouselimage',
            name='image_upload',
        ),
        migrations.AddField(
            model_name='carouselimage',
            name='image',
            field=models.ImageField(blank=True, help_text='Upload carousel image', null=True, upload_to=apps.core.models.carousel_upload_to),
        ),
    ]
