# Generated by Django 5.2.4 on 2026-05-19 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_carouselimage_image_upload_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DoctorVisitRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('doctor_name', models.CharField(max_length=100)),
                ('specialization', models.CharField(choices=[('General Physician', 'General Physician'), ('Cardiologist', 'Cardiologist'), ('Dermatologist', 'Dermatologist'), ('Pediatrician', 'Pediatrician'), ('Orthopedic', 'Orthopedic'), ('Gynecologist', 'Gynecologist'), ('ENT Specialist', 'ENT Specialist'), ('Neurologist', 'Neurologist'), ('Psychiatrist', 'Psychiatrist'), ('Ophthalmologist', 'Ophthalmologist'), ('Other', 'Other')], max_length=50)),
                ('hospital_name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=15)),
                ('address', models.TextField()),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('preferred_date', models.DateField()),
                ('preferred_time', models.CharField(choices=[('Morning', 'Morning (9:00 AM - 12:00 PM)'), ('Afternoon', 'Afternoon (12:00 PM - 3:00 PM)'), ('Evening', 'Evening (3:00 PM - 6:00 PM)')], max_length=20)),
                ('purpose', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Doctor Visit Request',
                'verbose_name_plural': 'Doctor Visit Requests',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProductCatalogue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(default='Product Catalogue', max_length=200)),
                ('description', models.TextField(blank=True)),
                ('pdf_file', models.FileField(upload_to='catalogues/')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Product Catalogue',
                'verbose_name_plural': 'Product Catalogues',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RetailerEnquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('business_name', models.CharField(max_length=200)),
                ('contact_person', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=15)),
                ('address', models.TextField()),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('pincode', models.CharField(max_length=10)),
                ('gst_number', models.CharField(blank=True, max_length=20)),
                ('estimated_order_value', models.CharField(choices=[('<50k', 'Less than 50,000'), ('50k-1L', '50,000 - 1 Lakh'), ('1L-5L', '1 Lakh - 5 Lakhs'), ('5L+', 'More than 5 Lakhs')], max_length=20)),
                ('message', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Retailer Enquiry',
                'verbose_name_plural': 'Retailer Enquiries',
                'ordering': ['-created_at'],
            },
        ),
    ]
