# Generated by Django 5.2.4 on 2026-03-24 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_carouselimage_image_data_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carouselimage',
            name='button_link',
            field=models.CharField(blank=True, help_text='Relative or absolute URL (e.g., /products/ or https://lifelinehealthcare.in/products/)', max_length=255),
        ),
    ]
