# Generated by Django 5.2.4 on 2026-03-24 11:55

import apps.core.models
import storages.backends.s3
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_carouselimage_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carouselimage',
            name='image',
            field=models.ImageField(blank=True, help_text='Upload carousel image', null=True, storage=storages.backends.s3.S3Storage(bucket_name='lifeline-media'), upload_to=apps.core.models.carousel_upload_to),
        ),
    ]
