# Generated by Django 5.2.4 on 2026-05-20 03:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_doctorvisitrequest_productcatalogue_retailerenquiry'),
        ('core', '0007_alter_carouselimage_image'),
    ]

    operations = [
    ]
